### ISSUE TITLE
Taxonomic names from CSV/TSV -> OpenTree OTUs -> Tree -> NeXML

### ISSUE THREAD

**Issue by gaurav** [OpenTreeOfLife/hackathon#18]
This is a subproject of #16. I'm currently [close to finishing a Python script](https://github.com/gaurav/bettertaxonomy/) designed to match names against multiple taxonomic sources, using other information contained in the file to pick sources to match against -- for example, a name in class Mammalia could be matched against the Mammal Species of the World, ITIS, and the Catalogue of Life, while a name in class Aves would be matched against global bird checklists, ITIS and the Catalogue of Life.

It'd be pretty easy to add support for the [OpenTree taxonomy](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#taxonomy-methods) as a taxonomic source, but it'd be MUCH cooler to take the output of my script, [get a pruned subtree](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#synthetic-tree-methods) from the OpenTree synthesized tree, and then add the metadata already contained into the input CSV file back into the final NeXML file.

This would also fit neatly with #17, as PhyloStyloTastic would then be able to render the NeXML along with its included metadata.

**Comment by rvosa** [comment]
For the BioVeL project we have developed a web service that folds CSV/TSV and/or JSON into NeXML. There are some conventions for specifying what objects to annotate, but it might be useful: https://www.biodiversitycatalogue.org/services/70

**Comment by arlin** [comment]
Can we combine this with issue #2 ?   And possibly also with #1?

**Comment by gaurav** [comment]
Definitely similar to #2! Closing.
